#+TITLE: Adam Miezianko's Emacs Configuration

I am rebuilding my Emacs config from scratch. I used to use spacemacs and then
Doom emacs but both of those were too different from my Emacs experience in the
90s and early 00s. So, tabula rasa.

* About Me

Things Emacs should know about me. Currently just my latitude and longitude
so calendar knows when sunrise and sunset are.

#+BEGIN_SRC emacs-lisp
  (setq calendar-latitude 47.6062
	calendar-longitude -122.3321)

  (defconst my/laptop-p (equal (system-name) "algos.lan"))
#+END_SRC

* Packages

#+BEGIN_SRC emacs-lisp
  (require 'package)

  (setq package-archives
	'(("gnu" . "http://elpa.gnu.org/packages/")
	  ("melpa" . "https://melpa.org/packages/")))

  (package-initialize)

  (unless package-archive-contents
    (package-refresh-contents))

  ;; use-package allows for cleaner configuration of packages
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)

  ;; Causes use-package function to install packages not yet installed. Useful
  ;; when running this init.el on a system for the first time.
  (setq use-package-always-ensure t)
#+END_SRC

* Basic Look and Feel

  Remove extraneous user interface elements. Since the macOS menu bar is
  unobtrusive, don't hide it there.

#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (when (not (eq system-type 'darwin))
    (menu-bar-mode -1))

  (setq inhibit-startup-message t)
  (setq visible-bell t)


  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

For themes I jump between zenburn and leuven.

#+BEGIN_SRC emacs-lisp
  (use-package zenburn-theme
    :config (load-theme 'zenburn t)
  )
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'darwin)
    ;; Fixes TLS issues on macOS
    (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
    (setq mac-command-modifier 'meta)
    (setq mac-option-modifier 'none)
    (setq w3m-command "/usr/local/bin/w3m"))


  ;; I seperate my sentences with one space not two.
  (setq sentence-end-double-space nil)

  ;; Change this to Sasha Chua's backup strategy of using a directory
  (setq make-backup-files nil)

  (set-face-attribute 'default nil :font "Go Mono" :height 140)

  (setq custom-safe-themes t)

  (global-hl-line-mode 1)

  (blink-cursor-mode -1)

  (setq shift-select-mode nil)

  (setq-default fill-column 80)
  (setq-default sentence-end-double-space nil)


  (show-paren-mode 1)

  ;; Emacs doesn't provide enough terminal support for pagers like less, but we
  ;; don't need pagers since we have a buffer. We can just use cat instead.
  (setenv "PAGER" "/bin/cat")

  (use-package w3m)

  ;;; ido-mode
  (ido-mode 1)
  (setq ido-everywhere t)
  (setq ido-enable-flex-matching t)

  ;;; fido-mode
  ;; (fido-mode 1)

  ;;; Helm
  (use-package helm)

  (define-key emacs-lisp-mode-map
    (kbd "M-.") 'find-function-at-point)

  (eldoc-mode 1)

  (use-package magit)

  ;; rebinding M-i (tab-to-tab-stop) to something I use more often: imenu
  (global-set-key (kbd "M-i") 'imenu)


  ;; Goal column is handy (C-x C-n)
  (put 'set-goal-column 'disabled nil)
#+END_SRC

* Org Mode

#+begin_src emacs-lisp
  ;; Org-mode configuration

  (setq org-agenda-files '("~/memex"))
  (setq-default org-adapt-indentation 'headline-data)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)

  (define-key global-map (kbd "C-c a") 'org-agenda)
  (define-key global-map (kbd "C-c l") 'org-store-link)
#+end_src

I track how long I work on tasks using the Pomodoro technique.

#+begin_src emacs-lisp
  (setq org-log-done t)

  (use-package org-pomodoro
    :bind ("C-c p" . org-pomodoro))
#+end_src

* Python

Settings that are specific not just to the OS but individual machine.

#+BEGIN_SRC emacs-lisp
  (if my/laptop-p
      (setq-default python-shell-interpreter "/usr/local/bin/python3"))
#+END_SRC

* References

These are the configurations where I go to discover new ideas and learn more
elisp.

- [[https://github.com/caisah/emacs.dz?utm_source=pocket_mylist][A list of people with nice emacs config files]]
- [[https://github.com/purcell/emacs.d][Steve Purcell's config]] :: 
- [[https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org][Sacha Chua's config]] :: A literate configuration with many explanations.
- [[https://github.com/bbatsov/prelude][prelude]] :: More of a starter pack. Sane defaults for many things.
- [[https://en.wikipedia.org/wiki/User%3AGwern%2F.emacs][Gwern Branwen's config]] :: Edits a lot of markdown.
